# Generated by Django 6.0.4 on 2026-05-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='document',
            field=models.FileField(blank=True, help_text='Upload ID proof or skill certificate for verification', null=True, upload_to='provider_documents/'),
        ),
    ]
