# Generated by Django 6.0.4 on 2026-05-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_serviceprovider_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='skill',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
