# Generated by Django 5.2.7 on 2026-06-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_alter_serviceprovider_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
