# Generated by Django 6.0.4 on 2026-05-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_completed_at_booking_is_disputed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='chat_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
